### ISSUE TITLE
Create a Payment Page.

### ISSUE THREAD

**Issue by yigiaom** [cse442-at-ub/project_s23-one-belt-one-road#23]
**Task tests**

*Test 1*
1) Open the 'payment.php' file in VS Code which will open a web page about the payment page.
2) Verify if there are Address, Full name, Phone number, City, State and Zip code, Card number, Name on card and Expiration date text boxes.
3) In the HTML code for the payment page, verify if a tag of input type="text", with id "address" exists.
4) In the HTML code for the payment page, verify if a tag of input type="text", with id "name" exists.
5) In the HTML code for the payment page, verify if a tag of input type="text", with id "phone" exists.
6) In the HTML code for the payment page, verify if a tag of input type="text", with id "city" exists.
7) In the HTML code for the payment page, verify if a tag of input type="text", with id "state " exists.
8) In the HTML code for the payment page, verify if a tag of input type="text", with id "zipcode" exists.
9) In the HTML code for the payment page, verify if a tag of input type="text", with id "cardnumber" exists.
10) In the HTML code for the payment page, verify if a tag of input type="text", with id "cardname" exists.
11) In the HTML code for the payment page, verify if a tag of input type="text", with id "expiration" exists.

*Test 2*
1) Open the 'paymentpage.php' file in VS Code which will open a web page about the payment page.
2) Verify if there is a "Confirm Order" button at the bottom.
3) In the HTML code for the payment page, verify if a tag of button with name "Confirm Order" exists.

**Comment by anht-11** [comment]
"If a task is added to the Planned pipeline in one sprint, but does not get developed in that time, DO remove the original sprint label and replace it with the label from the new sprint." - Style Guide

A task should not be blocked by any issue (task or user story), so you might want to remove any task currently blocking this task. 

Also, I suggest we group all tasks related to the payment page to one task only, so it would be easy to run multiple task tests on one issue, instead of jumping around tasks.
