### ISSUE TITLE
[DELETED] UNRELATED ISSUE

### ISSUE THREAD

**Issue by JiajunGao88** [cse442-at-ub/project_s23-one-belt-one-road#89]
**Task Test**

*Test 1*

1. Load the product detail page for a sample product.
2. Login with an account username "asddsa" password "asddsaasd" which has userid=36 and make sure login successfully.
3. Verify that the "add to cart" button is visible and clickable.
4. Click on the "add to cart" button and verify that the product is added to the cart.
5. Verify that the cart item count is updated correctly in database.
6. Simulate navigating to the cart page and verify that the product is displayed correctly.
7. Repeat steps 2-6 with different product to simulate different user behaviors (e.g., adding multiple products, etc.).

**Comment by anht-11** [comment]
As the task tests are verified by the developer, can we include specific file for product detail page the developer should look at to verify implementation?

**Comment by anht-11** [comment]
If I understand correctly, you are testing both front-end and database at the same time. Can we split these types of tests into different tests, instead of combining into one test?

Also step 9 are more of acceptance tests that untrained user might trigger various different scenarios. Should we include these types of tests in the user story instead?
